In [2]:
import pandas as pd
import numpy as np

In [4]:
# Data frame
data = {
    'Episode': list(range(1, 17)),
    'Season 1': [4.64, 3.89, 4.53, 4.38, 4.38, 4.44, 4.03, 3.96, 4.45, 3.82, 3.96, 3.47, np.nan, np.nan, np.nan, np.nan],
    'Season 2': [3.47, 3.80, 3.88, 3.70, 3.72, 3.89, 3.41, 3.42, 4.00, 4.48, 3.57, 3.75, 3.36, 3.07, 2.90, 3.20],
    'Season 3': [2.93, 2.89, 2.48, 2.99, 2.79, 2.76, 2.79, 3.52, 2.95, 3.16, 2.28, 2.28, 2.35, 2.53, 2.50, 2.40],
    'Season 4': [2.50, 2.65, 2.76, 2.42, 2.33, 2.70, 2.81, 2.59, 2.59, 2.76, 1.87, 1.67, 1.46, 1.70, 1.80, 1.55],
    'Season 5': [2.13, 2.27, 2.16, 2.38, 2.10, 2.16, 2.08, 2.31, 2.30, 2.34, 1.74, 1.51, 1.71, 1.58, 1.73, 1.71],
    'Season 6': [1.85, 1.65, 1.78, 1.81, 1.51, 1.68, 1.83, 1.88, 1.87, 1.92, 1.37, 1.53, 1.28, 1.21, 1.25, 1.13],
    'Season 7': [1.40, 1.36, 1.41, 1.41, 1.29, 1.47, 1.35, 1.51, 1.64, 1.68, 1.18, 1.06, 0.95, 0.99, 1.09, 1.07],
    'Season 8': [1.27, 1.18, 1.16, 1.09, 1.15, 1.22, 1.13, 1.30, 1.07, 1.08, 0.82, 0.91, 0.77, 0.78, 0.69, 0.74],
    'Season 9': [1.04, 1.04, 0.94, 1.00, 0.96, 1.05, 1.07, 0.97, 0.96, 0.86, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan], 
}

# Convert the dictionary to a DataFrame
df = pd.DataFrame(data)
df.set_index('Episode', inplace=True)

print(df)

         Season 1  Season 2  Season 3  Season 4  Season 5  Season 6  Season 7  \
Episode
1            4.64      3.47      2.93      2.50      2.13      1.85      1.40
2            3.89      3.80      2.89      2.65      2.27      1.65      1.36
3            4.53      3.88      2.48      2.76      2.16      1.78      1.41
4            4.38      3.70      2.99      2.42      2.38      1.81      1.41
5            4.38      3.72      2.79      2.33      2.10      1.51      1.29
6            4.44      3.89      2.76      2.70      2.16      1.68      1.47
7            4.03      3.41      2.79      2.81      2.08      1.83      1.35
8            3.96      3.42      3.52      2.59      2.31      1.88      1.51
9            4.45      4.00      2.95      2.59      2.30      1.87      1.64
10           3.82      4.48      3.16      2.76      2.34      1.92      1.68
11           3.96      3.57      2.28      1.87      1.74      1.37      1.18
12           3.47      3.75      2.28      1.67      1.51      1.53      1.06
13            NaN      3.36      2.35      1.46      1.71      1.28      0.95
14            NaN      3.07      2.53      1.70      1.58      1.21      0.99
15            NaN      2.90      2.50      1.80      1.73      1.25      1.09
16            NaN      3.20      2.40      1.55      1.71      1.13      1.07

         Season 8  Season 9
Episode
1            1.27      1.04
2            1.18      1.04
3            1.16      0.94
4            1.09      1.00
5            1.15      0.96
6            1.22      1.05
7            1.13      1.07
8            1.30      0.97
9            1.07      0.96
10           1.08      0.86
11           0.82       NaN
12           0.91       NaN
13           0.77       NaN
14           0.78       NaN
15           0.69       NaN
16           0.74       NaN

## Show Description 
*Suits* is a legal drama television series created by Aaron Korsh. Set in a fictional New York City law firm, the show follows the story of *Mike Ross*, a brilliant college dropout who starts working as a law associate for *Harvey Specter*, despite lacking a law degree. The series explores their unconventional partnership as they navigate the high-stakes legal world while keeping Mike's secret hidden. *Suits* delves into themes of ambition, loyalty, and the complexities of the legal profession, showcasing intricate legal cases alongside character-driven drama. With sharp wit, compelling storytelling, and memorable characters, *Suits* captivated audiences during its run.

![Suits](Suits.jpg)

## Summary of Ratings

In [9]:
df.describe()

,Season 1,Season 2,Season 3,Season 4,Season 5,Season 6,Season 7,Season 8,Season 9
count,12.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,16.000000,10.000000
mean,4.162500,3.601250,2.725000,2.260000,2.013125,1.596875,1.303750,1.022500,0.989000
std,0.355224,0.388036,0.347563,0.491501,0.297315,0.273025,0.225207,0.204206,0.063849
min,3.470000,2.900000,2.280000,1.460000,1.510000,1.130000,0.950000,0.690000,0.860000
25%,3.942500,3.397500,2.460000,1.775000,1.725000,1.347500,1.085000,0.810000,0.960000
50%,4.205000,3.635000,2.775000,2.460000,2.115000,1.665000,1.355000,1.085000,0.985000
75%,4.442500,3.820000,2.935000,2.662500,2.277500,1.835000,1.425000,1.165000,1.040000
max,4.640000,4.480000,3.520000,2.810000,2.380000,1.920000,1.680000,1.300000,1.070000