In [2]:
import pandas as pd
import numpy as np

In [25]:


data = {
    'Season 1': [4.64, 3.89, 4.53, 4.38, 4.38, 4.44, 4.03, 3.96, 4.45, 3.82, 3.96, 3.47, np.nan, np.nan, np.nan, np.nan],
    'Season 2': [3.47, 3.80, 3.88, 3.70, 3.72, 3.89, 3.41, 3.42, 4.00, 4.48, 3.57, 3.75, 3.36, 3.07, 2.90, 3.20],
    'Season 3': [2.93, 2.89, 2.48, 2.99, 2.79, 2.76, 2.79, 3.52, 2.95, 3.16, 2.28, 2.28, 2.35, 2.53, 2.50, 2.40],
    'Season 4': [2.50, 2.65, 2.76, 2.42, 2.33, 2.70, 2.81, 2.59, 2.59, 2.76, 1.87, 1.67, 1.46, 1.70, 1.80, 1.55],
    'Season 5': [2.13, 2.27, 2.16, 2.38, 2.10, 2.16, 2.08, 2.31, 2.30, 2.34, 1.74, 1.51, 1.71, 1.58, 1.73, 1.71],
    'Season 6': [1.85, 1.65, 1.78, 1.81, 1.51, 1.68, 1.83, 1.88, 1.87, 1.92, 1.37, 1.53, 1.28, 1.21, 1.25, 1.13],
    'Season 7': [1.40, 1.36, 1.41, 1.41, 1.29, 1.47, 1.35, 1.51, 1.64, 1.68, 1.18, 1.06, 0.95, 0.99, 1.09, 1.07],
    'Season 8': [1.27, 1.18, 1.16, 1.09, 1.15, 1.22, 1.13, 1.30, 1.07, 1.08, 0.82, 0.91, 0.77, 0.78, 0.69, 0.74],
    'Season 9': [1.04, 1.04, 0.94, 1.00, 0.96, 1.05, 1.07, 0.97, 0.96, 0.86, np.nan, np.nan, np.nan, np.nan, np.nan, np.nan],
}

# Creating a range of years starting from 2011
years = pd.date_range(start='2011', periods=len(data), freq='Y')

# Creating the DataFrame
df = pd.DataFrame(data)

# Transposing the DataFrame and setting the index
df = df.T
df.columns.name = 'Season number'
df.index = ['Season ' + str(i+1) for i in range(len(df))]

# Adding the 'Date' column
df['Date'] = years.year

df

Season number,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,Date
Season 1,4.64,3.89,4.53,4.38,4.38,4.44,4.03,3.96,4.45,3.82,3.96,3.47,NaN,NaN,NaN,NaN,2011
Season 2,3.47,3.80,3.88,3.70,3.72,3.89,3.41,3.42,4.00,4.48,3.57,3.75,3.36,3.07,2.90,3.20,2012
Season 3,2.93,2.89,2.48,2.99,2.79,2.76,2.79,3.52,2.95,3.16,2.28,2.28,2.35,2.53,2.50,2.40,2013
Season 4,2.50,2.65,2.76,2.42,2.33,2.70,2.81,2.59,2.59,2.76,1.87,1.67,1.46,1.70,1.80,1.55,2014
Season 5,2.13,2.27,2.16,2.38,2.10,2.16,2.08,2.31,2.30,2.34,1.74,1.51,1.71,1.58,1.73,1.71,2015
Season 6,1.85,1.65,1.78,1.81,1.51,1.68,1.83,1.88,1.87,1.92,1.37,1.53,1.28,1.21,1.25,1.13,2016
Season 7,1.40,1.36,1.41,1.41,1.29,1.47,1.35,1.51,1.64,1.68,1.18,1.06,0.95,0.99,1.09,1.07,2017
Season 8,1.27,1.18,1.16,1.09,1.15,1.22,1.13,1.30,1.07,1.08,0.82,0.91,0.77,0.78,0.69,0.74,2018
Season 9,1.04,1.04,0.94,1.00,0.96,1.05,1.07,0.97,0.96,0.86,NaN,NaN,NaN,NaN,NaN,NaN,2019

## Show Description 
*Suits* is a legal drama television series created by Aaron Korsh. Set in a fictional New York City law firm, the show follows the story of *Mike Ross*, a brilliant college dropout who starts working as a law associate for *Harvey Specter*, despite lacking a law degree. The series explores their unconventional partnership as they navigate the high-stakes legal world while keeping Mike's secret hidden. *Suits* delves into themes of ambition, loyalty, and the complexities of the legal profession, showcasing intricate legal cases alongside character-driven drama. With sharp wit, compelling storytelling, and memorable characters, *Suits* captivated audiences during its run.

![Suits](Suits.jpg)

## Summary of Ratings

In [26]:
df.describe()

Season number,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,Date
count,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,9.000000
mean,2.358889,2.303333,2.344444,2.353333,2.247778,2.374444,2.277778,2.384444,2.425556,2.455556,2.098750,2.022500,1.697143,1.694286,1.708571,1.685714,2015.000000
std,1.169406,1.083836,1.221005,1.169615,1.191719,1.185919,1.047280,1.065823,1.214816,1.219048,1.124601,1.064985,0.898104,0.833724,0.783697,0.856794,2.738613
min,1.040000,1.040000,0.940000,1.000000,0.960000,1.050000,1.070000,0.970000,0.960000,0.860000,0.820000,0.910000,0.770000,0.780000,0.690000,0.740000,2011.000000
25%,1.400000,1.360000,1.410000,1.410000,1.290000,1.470000,1.350000,1.510000,1.640000,1.680000,1.322500,1.397500,1.115000,1.100000,1.170000,1.100000,2013.000000
50%,2.130000,2.270000,2.160000,2.380000,2.100000,2.160000,2.080000,2.310000,2.300000,2.340000,1.805000,1.600000,1.460000,1.580000,1.730000,1.550000,2015.000000
75%,2.930000,2.890000,2.760000,2.990000,2.790000,2.760000,2.810000,3.420000,2.950000,3.160000,2.602500,2.577500,2.030000,2.115000,2.150000,2.055000,2017.000000
max,4.640000,3.890000,4.530000,4.380000,4.380000,4.440000,4.030000,3.960000,4.450000,4.480000,3.960000,3.750000,3.360000,3.070000,2.900000,3.200000,2019.000000